### ISSUE TITLE
Problem about documentation.

### ISSUE THREAD

**Issue by brsilvarec** [ajwdewit/pcse#20]
Hello Folks,

Apparently, there is a problem about the description of irrigation signal in the documentation. In the documentation, the irrigation should be defined in this way.

Version: 1.0
AgroManagement:
- 1999-09-01:
  CropCalendar:
      crop_id: winter-wheat
      crop_start_date: 1999-10-01
      crop_start_type: sowing
      crop_end_date: 2000-08-05
      crop_end_type: harvest
      max_duration: 330
  TimedEvents:
  -   event_signal: irrigate
    name:  Timed irrigation events
    comment: All irrigation amounts in cm
    events_table:
    - 2000-05-01: {irrigation_amount: 2, efficiency: 0.7}
    - 2000-06-21: {irrigation_amount: 5, efficiency: 0.7}
    - 2000-07-18: {irrigation_amount: 3, efficiency: 0.7}
      StateEvents:

However,

The callback function to treat the irrigation signal is this.

 `def _on_IRRIGATE(self, amount, efficiency):
        self._RIRR = amount * efficiency`

Observe that the name of the irrigation_amount parameter is amount not irrigation_amount as described in the documentation.

then I get this error

`TypeError: _on_IRRIGATE() takes exactly 3 arguments (2 given)
Uncaught exception. Entering post mortem debugging`

 when using the Wofost71_WLP_FD model and had to change the agromanager to 

Version: 1.0
AgroManagement:
- 1999-09-01:
  CropCalendar:
      crop_id: winter-wheat
      crop_start_date: 1999-10-01
      crop_start_type: sowing
      crop_end_date: 2000-08-05
      crop_end_type: harvest
      max_duration: 330
  TimedEvents:
  -   event_signal: irrigate
    name:  Timed irrigation events
    comment: All irrigation amounts in cm
    events_table:
    - 2000-05-01: {amount: 2, efficiency: 0.7}
    - 2000-06-21: {amount: 5, efficiency: 0.7}
    - 2000-07-18: {amount: 3, efficiency: 0.7}
      StateEvents:

To get the desired result.

Thanks

**Comment by ajwdewit** [comment]
Hi

thanks for notifying me of this omission. I will try to fix it in the 
coming days.

regards,

Allard

**Comment by ajwdewit** [comment]
It has been fixed in the develop branch and is updated in the 'latest' documentation on readthedocs (see here: http://pcse.readthedocs.io/en/latest/reference_guide.html#defining-agromanagement-in-pcse). It will automatically go to the stable and master documentation with the next releate.

Thanks,

Allard
