### ISSUE TITLE
Python 3 issue

### ISSUE THREAD

**Issue by brsilvarec** [ajwdewit/pcse#22]
Hello everyone,

   I am trying to install the PCSE in a python 3 virtual environment but I have no success. I am using python 3.5.2

![image](https://cloud.githubusercontent.com/assets/7769154/23179628/4d7abe78-f84d-11e6-9507-d6bb5e7ef590.png)

Apparently, you should import _pickle instead cPickle when the environment is python 3. 

Thank you all

**Comment by ajwdewit** [comment]
Sorry for the late response. 

the pickle/cPickle issue is indeed a nuisance. However, I though that this should be fixed automatically by the 2to3 tool when installing PCSE in a python 3 environment.

Allard

**Comment by tomyun** [comment]
Seems like `2to3` tool doesn't automatically pick up `cPickle` and `pickle` transition. You may want to try [six](https://pythonhosted.org/six/) as its `six.moves` takes care of such renamed modules.

Otherwise you can adopt a defensive strategy which should work both for Python 2 and 3. IIRC, this was an already [favored way](https://pymotw.com/2/pickle/) of using pickle in Python 2 era.

```python
try:
    import cPickle as pickle
except:
    import pickle
```

**Comment by ajwdewit** [comment]
thanks,

Sorry for the late reply. The 2 to 3 conversion is on my list, but have 
not got to it yet.

regards,

Allard

**Comment by SpiderTony** [comment]
Really need your help
I do not konw where to get the soil data and how to change the some of the data in crop file,could you please give me some help?

**Comment by ajwdewit** [comment]
Dear ..

Can you be a bit more specific? Where do you want to  apply WOFOST? 
Which crops?
This matters for the soil sources that I can suggest.

with best regards,

Allard

**Comment by SpiderTony** [comment]
I need to apply wofost in northeast of China.And the crop is maize




在2018年01月22日 20:03，Allard de Wit 写道:
Dear ..

Can you be a bit more specific? Where do you want to apply WOFOST?
Which crops?
This matters for the soil sources that I can suggest.

with best regards,

Allard

**Comment by ajwdewit** [comment]
Dear Tony

There is an implementation of CGMS for china which contains the soil 
data available from the FAO (1:5,000,000) which is pretty coarse.

https://wageningenur4-my.sharepoint.com/:u:/g/personal/allard_dewit_wur_nl/EWBrYYAZ4F5EhRN4e8ze9vgBjHjhcdb_ub3aP0QGULAXAA?e=dLjEKz

See here: 
http://marswiki.jrc.ec.europa.eu/agri4castwiki/index.php/Welcome_to_WikiMCYFS 
for an explanation of the database tables. The soil data in the database 
is exactly what WOFOST needs.

Better soil data is probably available from the China soil bureau.

with best regards,

Allard

**Comment by math64** [comment]
Hello everyone,

I have the same problem as @brsilvarec to install PCSE in a python 3 virtual environment. I work with the python 3.6.3 version on windows 10. I read all your comment before and I installed 2to3 and six libraries but the problem remains when I try to install pcse with the command **pip install pcse** : "ModuleNotFoundError: No module named 'cPickle'"
Is there anything that I forgot to do?  

![image](https://user-images.githubusercontent.com/37619457/37711980-c80fca16-2d12-11e8-993c-e5641f790cb9.png)

Thanks for your answer!
Best regards,

**Comment by ajwdewit** [comment]
Hi

install from the develop_py3 branch directly. This branch is fully 
compatible with python 3.6. The branch will be merged into the next 
release: PCSE 6.0

you can probably use:

  pip install https://github.com/ajwdewit/pcse/archive/develop_py3.zip

regards,

Allard

**Comment by SpiderTony** [comment]
Thanks for your reply!


发自网易邮箱大师
在2018年03月25日 05:20，Allard de Wit 写道:
Hi

install from the develop_py3 branch directly. This branch is fully
compatible with python 3.6. The branch will be merged into the next
release: PCSE 6.0

you can probably use:

pip install https://github.com/ajwdewit/pcse/archive/develop_py3.zip

regards,

Allard

**Comment by math64** [comment]
Dear Allard,

Thanks for your answer! It works fine now,

Best regards,
Mathieu

**Comment by shmulik90** [comment]
Unfortunately your branch doesn't work for me: 
![grafik](https://user-images.githubusercontent.com/38791059/40204433-14653d44-59ee-11e8-8cba-786cf1165dc7.png)

any ideas for missing module "traitlets_psce" ?

**Comment by ajwdewit** [comment]
the latest release 5.4.1 is fully python3 (>=3.4) compatible.
