### ISSUE TITLE
apply_npk event does not work

### ISSUE THREAD

**Issue by deademo** [ajwdewit/pcse#24]
I'm trying to modify agromanagement file for lintul3 model and change apply_npk values like this:
    StateEvents:
    -   event_signal: apply_npk
        event_state: DVS
        zero_condition: rising
        name: DVS-based N/P/K application table
        comment: all fertilizer amounts in kg/ha
        events_table:
        - 0.3: {N_amount : 1, P_amount: 3, K_amount: 4}
        - 0.6: {N_amount: 11, P_amount: 13, K_amount: 14}
        - 1.12: {N_amount: 21, P_amount: 23, K_amount: 24}
=>
    StateEvents:
    -   event_signal: apply_npk
        event_state: DVS
        zero_condition: rising
        name: DVS-based N/P/K application table
        comment: all fertilizer amounts in kg/ha
        events_table:
        - 0.3: {N_amount : 1, P_amount: 1, K_amount: 1}
        - 0.6: {N_amount: 4, P_amount: 4, K_amount: 4}
        - 1.12: {N_amount: 10, P_amount: 10, K_amount: 10}

I think WSO should be reduced in this case, but it didn't happen.
Also WSO doesn't changes if we increase N_amount, P_amount and K_amount.

Question is should WSO increase or decrease? Or it is a bug?

**Comment by ajwdewit** [comment]
Hi Dmitry

the LINTUL3 model does not support the use of P/K, it will respond only 
to N

Therefore, with this agromanagement definition, PCSE will broadcast an 
APPLY_NPK signal but LINTUL3 has no handler to receive it and therefore 
it will be ignored. Have a look at my example notebook here: 
https://github.com/ajwdewit/pcse_notebooks/blob/master/03%20running_LINTUL3.ipynb

Hope this helps

Allard

**Comment by deademo** [comment]
Thanks for your answer!
