### ISSUE TITLE
Providing DTEMP

### ISSUE THREAD

**Issue by sjbphd** [ajwdewit/pcse#28]
pcse.engine checks whether DTEMP is provided and if not, makes an approximation:
if not hasattr(drv, "DTEMP"):
            drv.add_variable("DTEMP", (drv.TEMP + drv.TMAX)/2., "Celcius")

However, DTEMP is not listed as an optional parameter in pcse.weather. Therefore, I cannot store it in a WeatherDataContainer to use in a simulation.

I think this is as simple as adding DTEMP to the list of optional parameters in pcse.weather.
I am new to Git, but I'm happy to make that change once I understand how pull requests work.

Cheers
Sam

**Comment by ajwdewit** [comment]
Dear Sam,

I think you are right, adding it to optional variables and with the 
appropriate range and units should make it available indeed.

If you change and test it I would be happy to accept the pull request.

Allard
