### ISSUE TITLE
NASAPowerWeatherProvider key error 'header'

### ISSUE THREAD

**Issue by KommandorKeen** [ajwdewit/pcse#31]
weatherdata = NASAPowerWeatherDataProvider(longitude=5, latitude=52)
print(weatherdata)
produces:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-25659be72013> in <module>
----> 1 weatherdata = NASAPowerWeatherDataProvider(longitude=5, latitude=52)
      2 print(weatherdata)

~\AppData\Local\Continuum\anaconda3\envs\py3_pcse\lib\site-packages\pcse\db\nasapower.py in __init__(self, latitude, longitude, force_update, ETmodel)
     96             self.logger.debug(msg)
     97             # No cache file, we really have to get the data from the NASA server
---> 98             self._get_and_process_NASAPower(self.latitude, self.longitude)
     99             return
    100 

~\AppData\Local\Continuum\anaconda3\envs\py3_pcse\lib\site-packages\pcse\db\nasapower.py in _get_and_process_NASAPower(self, latitude, longitude)
    139 
    140         # Store the informational header then parse variables
--> 141         self.description = [powerdata["header"]["title"]]
    142         self.elevation = float(powerdata["features"][0]["geometry"]["coordinates"][2])
    143         df_power = self._process_POWER_records(powerdata)

KeyError: 'header'

**Comment by ajwdewit** [comment]
Dear Simon.

I have seen this problem before when NASA POWER was down. Can you retry? 

With  best regard

Allard

Simon Allen <notifications@github.com> schreef op 26 februari 2020 00:52:29 CET:

**Comment by ajwdewit** [comment]
I will have a look at this issue so that it provides a more friendly message when NASA POWER fails.

**Comment by codename5281** [comment]
Hello @ajwdewit, 
I am having the exact same issue ; i did check on NASA Power homepage but there does not seem to have any particular service outage ? What do you think could be happening?
Thanks in advance !
