### ISSUE TITLE
easy way to display the meaning of output variables

### ISSUE THREAD

**Issue by krsnapaudel** [ajwdewit/pcse#36]
A lot of different abbreviations are used to refer to outputs of crop models.
I see LAIMAX, RD, TAGP, TWLV, TWRT, TWSO, TWST in summary output
and DVS,	LAI, TAGP, TWSO, TWLV, TWST, TWRT, TRA, RD,	 SM, WWLOW in the output.
For me, I cannot figure what all of these mean.

**Comment by ajwdewit** [comment]
Hi Dilli, they are provided in the back of the WOFOST User Manual: https://www.wur.nl/en/show/WOFOST-7.1-User-Manual.htm.
