### ISSUE TITLE
Improving WeatherDataProvider using interpolation

### ISSUE THREAD

**Issue by sulekahraman** [ajwdewit/pcse#37]
I think NASA is missing data for some dates, and when running WOFOST if there's a missing datapoint in the weather data, it fails with the following error:
`WeatherDataProviderError: No weather data for 2017-08-21.` 
It would be helpful to have some error handling or completing the gaps in the data using some sort of interpolation.

**Comment by Amarounek** [comment]
Hello! You can easily transfer NASA POWER data to dataframe by Pandas, interpolate and then reverse back to weather data containers. It is not so hard as it is looks ;-)

**Comment by mishagrol** [comment]
@Amarounek Hello! Can you show how to convert data from Pandas dataframe back to weather data containers? Thank!

For example I posted my code how to download NASA weather data, convert to pandas df and fill missed values

`from pcse.db import NASAPowerWeatherDataProvider`
`weather = NASAPowerWeatherDataProvider(51, 5, force_update=True)`
`df_weather = pd.DataFrame(weather.export())`
`print('initial number of days:', len(df_weather))`

here we do reindex of our dataset to add missed days
`r = pd.date_range(start=df_weather.DAY.min(), end=df_weather.DAY.max())`
`full_range_weather = df_weather.set_index('DAY').reindex(r).rename_axis('DAY').reset_index()`


lets fill them with fillforward or fillbackward
`filled_weather = full_range_weather.fillna(method='ffill', axis=0)`

show that we dont have missed values now
`print('now no NaN values:', filled_weather.isna().sum())`

**Comment by jjanggu1993** [comment]
@mishagrol Hello! Maybe there is a better solution, I think this code could be solution to you!

`weather._make_WeatherDataContainers(filled_weather.to_dict(orient="records"))`

**Comment by Amarounek** [comment]
Here's the code, you need to work with this function in class and import WeatherDataProvider to it...

`def weatherinverse(self):
        # Defining inverse function for returning dataframe to weather containers
        WeatherDataProvider.__init__(self)
        self.filled_dataset["DAY"] = pd.to_datetime(self.filled_dataset["DAY"], format="%Y-%m-%d")
        recs = self.filled_dataset.to_dict(orient="records")
        for rec in recs:
            wdc = WeatherDataContainer(**rec)
            self._store_WeatherDataContainer(wdc, wdc.DAY)`

**Comment by ajwdewit** [comment]
Thanks for the comments. I agree that it is technically relative simpel to fill up missing values (pandas fillna does the job). However, I am reluctant to implement this as standard behaviour because you may end up filling large holes in the NASA Power archive with considerable impact on your simulation results. I would prefer people to think about this before trying to "repair" missing records.

**Comment by Amarounek** [comment]
I completely agree Allard! Thank you for this warning. 

Actually, if I am writing some script, I always print the number of missing days. On the other, I am now thinking about some implementation of breaking off in case that huge amount of missing days will be in some short period of time... 

Anyway, I am using interpolate() more than pandas fillna....
