### ISSUE TITLE
Including the effect of changes in atmospheric CO2 concentration

### ISSUE THREAD

**Issue by YeanUk** [ajwdewit/pcse#46]
Hello, I'm trying to use PCSE/WOFOST to simulate climate change impacts on potatoes and include the effect of changes in atmospheric CO2 concentration on assimilation and transpiration. 

To do this, instead of changing AMAXTB, EFFTB, and transpiration-related parameters in input files, I made changes in "pcse\crop\wofost.py" as below and set CO2 values using WOFOST71SiteDataProvider:

From : 
from .assimilation import WOFOST_Assimilation as Assimilation
from .evapotranspiration import Evapotranspiration

To :
from .assimilation import WOFOST_Assimilation2 as Assimilation
from .evapotranspiration import EvapotranspirationCO2 as Evapotranspiration

Is it the right way? Or are there any other ways to include the CO2 effect?

Thank you in advance!

regards,

Yean-Uk

**Comment by cojacoo** [comment]
Hello,

I cannot tell what is the “right” way, but I did a couple of climate change scenarios using PCSE myself including and excluding CO2 fertilisation effects. To be honest, I strongly doubt that this can be used without proper reference. In my trials, the effect exceeded the observed bands of +7 to +15% yield for C3 plants (FACE experiment Thuenen Braunschweig). I tried to evaluate the model setups in this respect, but parameter interaction was too large to get down to such details. So basically I would expect it to remain rather difficult to come up with more reliable predictions...

All the best.
Conrad

**Comment by YeanUk** [comment]
Thank you for the quick response. Maybe I should consider just temperature and rainfall effects. 

Best regards,

Yean-Uk

**Comment by ajwdewit** [comment]
Hi Yean,

It is the right way. If you go to the "develop" branch of PCSE there is pcse.models.Wofost_80_PP_beta which includes the CO2 impact of assimilation and evapotranspiration. Nevertheless, I do agree with Conrad that modelling the impact of CO2 remains challenging. Initial experiments in greenhouses with high impact have been difficult to replicate with FACE experiments. The latter showed much lower impact of CO2. On the other hand, it is sometimes also suggested that current crop varieties are sink-limited and therefore may not be able to fully capture the benefits of increased atmospheric CO2. 

best regards
Allard

**Comment by YeanUk** [comment]
Thanks for the reply. I will try the configuration file when I get some data to evaluate the CO2 impacts. 

Best regards,

Yean-Uk
