### ISSUE TITLE
yaml safe load

### ISSUE THREAD

**Issue by S-lac** [ajwdewit/pcse#50]
Hi and thanks for the great package! 
I have been having a warning for a long time now, even though it doesn't result in any problem in simulations : 

#For : \pcse\fileinput\yaml_agro_loader.py:21
*YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.*

Replacing yaml.load() to yaml.safe_load() might to the trick if I am not mistaken.

**Comment by ajwdewit** [comment]
You are correct. It is fixed in the develop branch. I will upgrade to PCSE 5.5 in the coming weeks which will solve it.
