### ISSUE TITLE
Bug of wofost.get_summary_output()

### ISSUE THREAD

**Issue by BeingHapppy** [ajwdewit/pcse#57]
Hello everyone. 
I like use 
```python
wofost.get_summary_output()
```

 to get the summary of the WOFOST simulation, but sometimes it works, sometimes it does not work. 

![image](https://user-images.githubusercontent.com/42432428/136577919-bb4571f2-a216-46b3-9b6b-e559ede62dea.png)

This is the link for my code: https://github.com/BeingHapppy/bug_wofost_get_summary_output
 the main code is  test_bug.ipynb

My programming skills are too poor to solve this problem, thanks for any help!

**Comment by ajwdewit** [comment]
Hi,

Summary output is only generated when a crop cycle is finished. In your case, the crop does not reach maturity (DVS does not reach 2.0) or a harvest date. So there will not be summary output. You have to change the agromanagement definition. Most likely, the max_duration is too short.

Allard
