### ISSUE TITLE
TypeError: __init__() takes 4 positional arguments but 6 were given

### ISSUE THREAD

**Issue by rahul12hanotmeena** [ajwdewit/pcse#58]
I have followed your documentation  "Running PCSE/WOFOST with custom input data"
but I am facing the issue (TypeError: __init__() takes 4 positional arguments but 6 were given) during the implementation of your code

from pcse.models import Wofost71_WLP_FD
wofsim = Wofost71_WLP_FD(sitedata, timerdata, soildata, cropdata, wdp)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-c37b34b1c677> in <module>
----> 1 wofsim = Wofost71_WLP_FD(sitedata, timerdata, soildata, cropdata, wdp)

TypeError: __init__() takes 4 positional arguments but 6 were given

Can you help me ASAP

**Comment by ajwdewit** [comment]
I think you are using a very old version of the tutorial. Can you look at the latest PCSE notebooks on my github page?

Allard

rahul12hanotmeena ***@***.***> schreef op 24 november 2021 08:26:33 CET:
>I have followed your documentation  "Running PCSE/WOFOST with custom input data"
>but I am facing the issue (TypeError: __init__() takes 4 positional arguments but 6 were given) during the implementation of your code
>
>from pcse.models import Wofost71_WLP_FD
>wofsim = Wofost71_WLP_FD(sitedata, timerdata, soildata, cropdata, wdp)
>
>
>---------------------------------------------------------------------------
>TypeError                                 Traceback (most recent call last)
><ipython-input-26-c37b34b1c677> in <module>
>----> 1 wofsim = Wofost71_WLP_FD(sitedata, timerdata, soildata, cropdata, wdp)
>
>TypeError: __init__() takes 4 positional arguments but 6 were given
>
>Can you help me ASAP
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ajwdewit/pcse/issues/58
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
