### ISSUE TITLE
Can the wofost model output ET (actual evaporation)? 

### ISSUE THREAD

**Issue by lwq-star** [ajwdewit/pcse#63]
Hello, 
can the wofost model output ET (actual evaporation)? 
I would like to assimilate the ET's of the model, but I can't find the variable ET.

**Comment by lwq-star** [comment]
I see that the model can output TRA, can it be used as a substitute? 
I don't know much about the model yet and look forward to your answer.

**Comment by ajwdewit** [comment]
Hi, each model has a configuration file, see here: https://pcse.readthedocs.io/en/stable/reference_guide.html#engine-configuration-files
You can add variables to the list with OUTPUT_VARS. If you are interested in soil evaporation, this is the variable "EVS", crop transpiration "TRA" is already in the list.

**Comment by lwq-star** [comment]
Thanks, I can't find the variable "EVS" in the [examples](https://pcse.readthedocs.io/en/stable/code.html?highlight=Engine%20configuration%20files#) or the manual (Gentle intro WOFOST-7_2_v20210518.pdf) , only "EVSMX", "EVST".

I found "ET0", which is the potential evaporation rate, so is there an actual evaporation rate?

If there is no ET (actual evaporation rate), do I have to get it from plant transpiration rate and soil evaporation rate?

**Comment by lwq-star** [comment]
![image](https://user-images.githubusercontent.com/80203996/180342760-fd6a9814-ce35-49e2-990f-4bdca92c7d4c.png)
This is the PML_V2 0.1.7: Coupled Evapotranspiration and Gross Primary Product (GPP) in google earth engine, [see here](https://developers.google.com/earth-engine/datasets/catalog/CAS_IGSNRR_PML_V2_v017?hl=en#bands)

in this data ET (actual evaporation rate) = Ec + Es, I think in the wofost model ET = TRA + EVS (if this variable is available), am I correct?

Thank you for discussing this issue with me.

**Comment by ajwdewit** [comment]
EVST =  accumulated soil evaporation in cm. Variable EVS is the daily soil evaporation in cm/day


Allard

**Comment by lwq-star** [comment]
Thank you, I have managed to export them. 
Sorry to disturb you on holiday.
But I'm still wondering why I can't find the variable "EVS" in the description or the manual, 
it's only in the source code that they exist. 
Is there a full description of the model variables? 
As far as I can see Gentle intro WOFOST-7_2_v20210518.pdf and WOFOST_system_description.pdf are also incomplete.

**Comment by ymzh0405** [comment]
> Thank you, I have managed to export them. Sorry to disturb you on holiday. But I'm still wondering why I can't find the variable "EVS" in the description or the manual, it's only in the source code that they exist. Is there a full description of the model variables? As far as I can see Gentle intro WOFOST-7_2_v20210518.pdf and WOFOST_system_description.pdf are also incomplete.

I also wonder to know the output of EVS, do you know how to export EVS?

**Comment by lwq-star** [comment]
> > Thank you, I have managed to export them. Sorry to disturb you on holiday. But I'm still wondering why I can't find the variable "EVS" in the description or the manual, it's only in the source code that they exist. Is there a full description of the model variables? As far as I can see Gentle intro WOFOST-7_2_v20210518.pdf and WOFOST_system_description.pdf are also incomplete.
> 
> I also wonder to know the output of EVS, do you know how to export EVS?

EVST =  accumulated soil evaporation in cm. Variable EVS is the daily soil evaporation in cm/day

**Comment by ymzh0405** [comment]
> > > Thank you, I have managed to export them. Sorry to disturb you on holiday. But I'm still wondering why I can't find the variable "EVS" in the description or the manual, it's only in the source code that they exist. Is there a full description of the model variables? As far as I can see Gentle intro WOFOST-7_2_v20210518.pdf and WOFOST_system_description.pdf are also incomplete.
> > 
> > 
> > I also wonder to know the output of EVS, do you know how to export EVS?
> 
> EVST = accumulated soil evaporation in cm. Variable EVS is the daily soil evaporation in cm/day

I tried use 'update_output_variable_lists' to add EVS into output, but I can not found EVS in my result.
config_loader = ConfigurationLoader('Wofost72_WLP_CWB.conf')
config_loader.update_output_variable_lists(
output_vars=['EVS']
)
