### ISSUE TITLE
Can't load weather data correctly using Excel

### ISSUE THREAD

**Issue by NickAlexander18** [ajwdewit/pcse#64]
I'm trying to load my weather data into Wofost72_WLP_FD. 
The ExcelWeatherDataProvider can read the data and show the description like follows:

![image](https://user-images.githubusercontent.com/52007523/180651429-1933cbf4-08ef-4c4a-b40e-0179a366830c.png)

It shows that: 
"Data available for 2007-01-01 - 2008-12-31
Number of missing days: 0"

However, when I run the Wofost72_WLP_FD, it occurs that "No weather data for 2017-01-01.".
![image](https://user-images.githubusercontent.com/52007523/180651854-f3b49dd3-3465-40b4-9b96-38d8669fefa4.png)

At first I thought it was because of the format of data in Excel, then I made it as same as the format of nl1.xlsx of official but didn't make it. The format of part of data is below: 
![image](https://user-images.githubusercontent.com/52007523/180652042-1732240c-b1f6-4f35-bf4d-072f5a6332ca.png)

How can I make it work?Thanks for help!

**Comment by S-lac** [comment]
Hey @NickAlexander18 How did you manage to handle this? Thanks
