### ISSUE TITLE
set_variable(variablename, newvalue) is invalid 

### ISSUE THREAD

**Issue by YueZhang99** [ajwdewit/pcse#66]
I want to update the state variable "TWSO" according to my observational data. 
To achieve my goal, I wrote a brief function in class WOFOST_Storgan_Dynamics(SimulationObject) :

def _set_variable_TWSO(self, nTWSO):
    states = self.states
    oTWSO = states.TWSO
    states.TWSO = nTWSO
    increments = {"TWSO": states.TWSO - oTWSO}
    return increments

In my own pcse projection, I used the following code to update "TWSO":

increasement = model.set_variable("TWSO", my_observation)

The code was processed successfully without no errors. But when I checked the final results, I found that the value wasn't updated at all! Is there anything I missed?  I really need your help.

**Comment by ajwdewit** [comment]
There is already a set_variable that updates the storage organ weights, see here: https://github.com/ajwdewit/pcse/blob/master/pcse/crop/storage_organ_dynamics.py#L141. so you do not have to write it yourself

Your approach for updating the value of TWSO is OK, from a code point of view. However, TWSO is computed as the sum of WSO and DWSO (dead WSO), the latter is always zero in the current WOFOST implementation. So at each time-step TWSO is recalculated and updating TWSO with a set_variable does not help as its values is overwritten by the sum of WSO and DWSO. 

So for having an effect on TWSO, you should update the WSO variable, not TWSO. This is a bit confusing but there are quite some variables where this could happen.

Allard

**Comment by YueZhang99** [comment]
Problem solved! I sincerely appreciate your help!

I haven't followed the code updates since I installed the PCSE environment, so I didn't notice that set_variable_WSO was already there until you told me. This made me realize the importance of keeping up with the code updates. And I also need to pay more attention to the principles and calculation order of PCSE.

Thank you again for your kind help!
