### ISSUE TITLE
"set_variable" function invalid for wofost8 version models

### ISSUE THREAD

**Issue by AlChen94** [ajwdewit/pcse#68]
When I was following the "pcse_notebooks-master" to test the data assimilation algorithm using the wofost8 crop model, I found that the "set_variable" function was invalid for it. Further tests show that all crop models of wofost8 version have this problem.

**Comment by AlChen94** [comment]
I noticed that "set_variable" works fine to "SM, WSO, WST, WRT", but still invalid to "LAI".

**Comment by ajwdewit** [comment]
Thanks for notifying me about this. I will have a look, however we are also preparing a redesign of WOFOST8 with regard to nutrient dynamics so it may have to wait before we push the new version.

**Comment by Acarlier-Osiris** [comment]
Hi, 

This is not actually corrected isn't it?

**Comment by ajwdewit** [comment]
Sorry, no I have not looked into the issue because of lack of time. I see that the _set_variable_LAI method is not implemented on the class WOFOST_Leaf_Dynamics_N. I will discuss it with my colleague whether this is on purpose or something that was forgotten in the process.

Allard
