### ISSUE TITLE
There may be some error in chapter 4.1.4 of doc

### ISSUE THREAD

**Issue by cleanhun13** [ajwdewit/pcse#69]
The example of an aromanagement definition file:
Original text
...
envents_table:
- 2000-05-25: {amount: 3.0, efficiency=0.7}
...
This kind of setting didn't work on Wofost72_WLP_FD

Revised text?
...
envents_table:
- 2000-05-25: {amount: 3.0, efficiency: 0.7}
...

**Comment by ajwdewit** [comment]
Hi 

You have an error in the yaml. It should be 'efficiency: 0.7'

Let me know if it helps.

Allard

cleanhun13 ***@***.***> schreef op 9 december 2022 13:31:13 CET:
>The example of an aromanagement definition file:
>Original text
>...
>envents_table:
>- 2000-05-25: {amount: 3.0, efficiency=0.7}
>...
>This kind of setting didn't work on Wofost72_WLP_FD
>
>
>Revised text?
>...
>envents_table:
>- 2000-05-25: {amount: 3.0, efficiency: 0.7}
>...
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ajwdewit/pcse/issues/69
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by cleanhun13** [comment]
Thanks, it helps.
