### ISSUE TITLE
Compatibility issue with python 3.10

### ISSUE THREAD

**Issue by pedroalencar1** [ajwdewit/pcse#70]
I recently updated my python to 3.10 and after installing pcse with `pip install pcse` couldn't import. 

The error is: "cannot import name 'Iterable' from 'collections'"

I looked up for the error up and found ([link to SO post](https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python)) `Iterable` from `collections` was deprecated and that one should use `collections.abc`.

Does it make sense?

Cheers,

**Comment by pedroalencar1** [comment]
Dear Allard, 

I don't know why, but I didn't get a notification of your answer. I did downgrade to 3.9 and have been working fine with it. 

Many thanks, 

Pedro

**Comment by ajwdewit** [comment]
I pushed version 5.5.5 to PyPI that is compatible with python 3.10
