### ISSUE TITLE
Bug in YAMLCropDataProvider.pkl

### ISSUE THREAD

**Issue by NickAlexander18** [ajwdewit/pcse#71]
Dear Allard,

When I use the WOFOST_crop_parameters-master, the YAMLCropDataProvider will use the .pkl cache first if there is YAMLCropDataProvider.pkl in the folder and raise an exception as follows:

![image](https://user-images.githubusercontent.com/52007523/218734865-4afc3abd-8161-449c-90e9-b93553bf4f17.png)

The exception doesn't affect the program, but sometimes annoys me if I use multiprocessing to run PCSE like this:

![image](https://user-images.githubusercontent.com/52007523/218735718-de0f78e7-07ee-4625-a0ef-bc70fbde54aa.png)

I've tried to delete the YAMLCropDataProvider.pkl, but it works only once and then raises the exception as usual

My PCSE version is 5.5.3, hpping you can fix this issue.Thanks a lot!

**Comment by ajwdewit** [comment]
Hi NickAlexander,

Are you running multiple processes in parallel? Could it be related to file locks under windows? I have never seen it under Linux.

Allard

**Comment by NickAlexander18** [comment]
Hi Allard,

I do run multiple processes in parallel under windows, but I don't think that multiple processes are the point because I followed the pcse_notebooks and got the same output. Here are my codes:
`from pcse.fileinput import CABOFileReader`
`from pcse.base import ParameterProvider`
`from pcse.util import WOFOST72SiteDataProvider`
`from pcse.fileinput import YAMLCropDataProvider`

`sited = WOFOST72SiteDataProvider(WAV=20)`
`cropd = YAMLCropDataProvider(fpath="./data/WOFOST_crop_parameters-master/")`
`cropd.set_active_crop('maize', "Grain_maize_203")`
`soild = CABOFileReader("./data/soil/ec2.soil")`
`parameters = ParameterProvider(sitedata=sited, cropdata=cropd, soildata=soild)`
`print(parameters)`

And the output is:
`E:\wyj\WOFOST> e: && cd e:\wyj\WOFOST && cmd /C "C:\Users\dell\AppData\Local\Programs\Python\Python38\python.exe c:\Users\dell\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher 64708 -- e:\wyj\WOFOST\Test.py "`
`YAMLCropDataProvider - Failed to load cache file: [WinError 2] 系统找不到指定的文件。: 'barley'`
`ParameterProvider providing 112 parameters, 0 parameters overridden: dict_keys([]).`

I check the folder "WOFOST_crop_parameters-master" and there's nothing wrong
![image](https://user-images.githubusercontent.com/52007523/219616143-9477783a-c78d-4d03-b720-1ccd1d0bc55c.png)

Does it ring any bells with you?

**Comment by ajwdewit** [comment]
No, not really. I will try your example to see what happens.

**Comment by ajwdewit** [comment]
Hi
I cannot reproduce the problem. Could it be an old cache file? So if you delete the cache file and rerun the code, does the problem persist?

Allard

**Comment by NickAlexander18** [comment]
Hi Allard,
If I delete the cache file YAMLCropDataProvider.pkl and rerun the code, the problem will be solved.
![image](https://user-images.githubusercontent.com/52007523/219950984-ec636f5b-e296-4961-82c4-b261fbac2f08.png)
![image](https://user-images.githubusercontent.com/52007523/219951062-dbb0a5b5-0d45-45b9-8417-9e14c1eacc02.png)

However, after I rerun the code, the YAMLCropDataProvider.pkl shows up again and the problem persist.
![image](https://user-images.githubusercontent.com/52007523/219951158-6732519c-d9b3-45d0-a75d-b7f71926fab8.png)
![image](https://user-images.githubusercontent.com/52007523/219951132-608af7a9-b4f8-48de-82b0-bacc4a722f6d.png)

So I think there's something about the YAMLCropDataProvider.pkl makes this happened

Alexander

**Comment by ajwdewit** [comment]
Dear Alexander,

When I cannot reproduce the problem it is extremely difficult to solve. BTW, What is the translation of the message after the "" WinError 2" ?

**Comment by NickAlexander18** [comment]
Dear Allard,

My platform is VSCode+Python3.8.10 on Windows10, and the problem doesn't affect the program, maybe I can just leave it and focus on my study.

the translation of the message after the "WinError 2" is: The system cannot find the specified file

**Comment by ajwdewit** [comment]
Hi Alexander, 

I think the only option is that you debug through the YAMLCropDataProvider when it loads the cache file which is done here: https://github.com/ajwdewit/pcse/blob/master/pcse/fileinput/yaml_cropdataprovider.py#L169 and report to me what the problem is. Otherwise I cannot do anything. However, I can imagine that you have other things to do, so in that case just leave it and continue your study.

Allard

**Comment by NickAlexander18** [comment]
Dear Allard,

I find the line that raises the exception. It's https://github.com/ajwdewit/pcse/blob/master/pcse/fileinput/yaml_cropdataprovider.py#L177

as the image shows below, the list comprehesion [os.stat(fn).st_mtime for fn in yaml_file_names] can raise the exception, 
![image](https://user-images.githubusercontent.com/52007523/221493070-c2194679-315a-413a-b2f1-4334e00c04ca.png)

for further experiment, I use for loop to print the elements os.stat(fn).st_mtime, and it raise FileNotFoundError(tips: the translation of the message after the "WinError 2" is: The system cannot find the specified file):
![image](https://user-images.githubusercontent.com/52007523/221495121-96178c64-fab5-4025-8b91-3d128bfbe7cf.png)

**Comment by ajwdewit** [comment]
I will have a look, but it is still not entire clear to me why the file cannot be found when the cache file is generated from the original files.

**Comment by ajwdewit** [comment]
I pushed a new version 5.5.5. to PyPi. I could not find your problem directly but I added a check that signals when a file does not exists and raises an error. Maybe that helps finding out what goes wrong.
