### ISSUE TITLE
How can I calculate site parameters when using Wofost80_NWLP_FD_beta

### ISSUE THREAD

**Issue by sqwev** [ajwdewit/pcse#72]
As a non-native speaker, I am having difficulty understanding some of the technical terminology and would appreciate your assistance.

My version of WOFOST is 5.5.4, and there are currently no documents available for learning WOFOST80. I am trying to simulate the effects of nitrogen stress on maize growth using this model, but I am having trouble inputting the required parameters. The parameters I am struggling with are NSOILBASE, NSOILBASE_FR, PSOILBASE, PSOILBASE_FR, KSOILBASE, KSOILBASE_FR, NAVAILI, PAVAILI, KAVAILI, BG_N_SUPPLY, BG_P_SUPPLY, and BG_K_SUPPLY.

My experimental data includes measurements of hydrolyzable nitrogen, available phosphorus, available potassium, pH, total nitrogen, soil bulk density, porosity, field water capacity, saturated water content, and the percentages of sand, silt, and clay particles. I would like to know how to calculate the input values for the parameters mentioned above based on this data.

Additionally, I have a few specific questions regarding the parameters. Firstly, I would like to know what NAVAILI refers to. Does it refer to the hydrolyzable nitrogen content at the time of sowing? Secondly, does NSOILBASE refer to the total nitrogen content of the soil minus the hydrolyzable nitrogen content? Lastly, how should I determine the value of NSOILBASE_FR?

**Comment by ajwdewit** [comment]
Hi, 

please have a look at the documentation of the SiteDataProvider: https://github.com/ajwdewit/pcse/blob/master/pcse/util.py#L1023 which defines the parameters. Nevertheless, I fully agree with you that the documentation for WOFOST 8.0 is not exhaustive yet. Regarding your question on how to compute these parameters, contact my colleague Herman Berghuijs: herman.berghuijs@wur.nl who is more familiar with nutrient calculations than I am.

Allard

**Comment by sqwev** [comment]
> 

Thank you for your help and contribution to the WOFOST model. I will seek further assistance from Dr. Herman Berghuijs.
