### ISSUE TITLE
Need for Angstrom factors even if HasSunshine=False

### ISSUE THREAD

**Issue by glemoine62** [ajwdewit/pcse#75]
I provide IRRAD values derived from ERA5 SiS Agmet daily solar_radiation_flux and (therefore) set HasSunshine=False, also because I do not know the Angstrom factors for my particular area (so I filled in dummies, because they are still required). However, pcse still checks these factors, so they must obey the validity range. The check should depend on HasSunshine.
(I use CSVWeatherDataProvider)

Minor nuisance.

**Comment by ajwdewit** [comment]
Hi Guido,

Thanks for your remark and I agree that the need to have the Angstrom coefficients is a bit of nuisance. However, your remark is not entirely true, the Angstrom equation is used in the Penman equation here: https://github.com/ajwdewit/pcse/blob/master/pcse/util.py#L183 Although we do not rely on the Penman equation for the crop reference ET, we still use if for the bare soil ET and open water ET. 

Nevertheless, I will have a look at it to see if there are alternative formulations of the Penman equation that do not require the Angstrom A/B parameters.

Allard
