### ISSUE TITLE
possibilities to define a time frame

### ISSUE THREAD

**Issue by frank0434** [ajwdewit/pcse#76]
Dear @ajwdewit 
wonder if it is possible to define a start and end date for retrieving NASA power climate data. The current `NASAPowerWeatherDataProvider` seems only accept coordinates and download all available data from the portal.  
https://github.com/ajwdewit/pcse/blob/7daa80a055f8721493afe42bf1dbce4f7eb3e92b/pcse/db/nasapower.py#L77

thank you

**Comment by ajwdewit** [comment]
Hi Jian

You are correct it always pulls all data from NASA Power. But it would be relatively easy to add a start/end date. See here: https://github.com/ajwdewit/pcse/blob/7daa80a055f8721493afe42bf1dbce4f7eb3e92b/pcse/db/nasapower.py#L210

Allard


"Jian (AKA Frank) Liu" ***@***.***> schreef op 11 juli 2023 11:33:27 CEST:
>Dear @ajwdewit 
>wonder if it is possible to define a start and end date for retrieving NASA power climate data. The current `NASAPowerWeatherDataProvider` seems only accept coordinates and download all available data from the portal.  
>https://github.com/ajwdewit/pcse/blob/7daa80a055f8721493afe42bf1dbce4f7eb3e92b/pcse/db/nasapower.py#L77
>
>thank you 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ajwdewit/pcse/issues/76
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
