### ISSUE TITLE
Can't input value 0 in sunshine value

### ISSUE THREAD

**Issue by sqwev** [ajwdewit/pcse#79]
when I load weather file in excel format, and set HasSunshine=True, pcse5.5.5 can't support the value of sunshine =0. So I wonder if this setting is reasonable, the code is in the file `pcse\fileinput\excelweatherdataprovider.py` line 173, `if 0 < value < 24:`

**Comment by ajwdewit** [comment]
Yes you are right. In principle it could be zero or 24 so I will change it into 0 <= value <= 24
