### ISSUE TITLE
The NASA power seems to be unusable

### ISSUE THREAD

**Issue by shuaijieshen** [ajwdewit/pcse#85]
The NASA power seems to be unusable with the error:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='power.larc.nasa.gov', port=443): Max retries exceeded with url: /api/temporal/daily/point?request=execute&parameters=TOA_SW_DWN%2CALLSKY_SFC_SW_DWN%2CT2M%2CT2M_MIN%2CT2M_MAX%2CT2MDEW%2CWS2M%2CPRECTOTCORR&latitude=35.5&longitude=116.5&start=20000101&end=20240202&community=AG&format=JSON&user=anonymous (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1135)'))))

During handling of the above exception, another exception occurred:

**Comment by ajwdewit** [comment]
This seems to be a temporary issue with NASA POWER. I tested and it is is working now.
