### ISSUE TITLE
Code problem about PCSE water balance module

### ISSUE THREAD

**Issue by Carolinecjh** [ajwdewit/pcse#86]
Dear ajwdewit,
When examining the `class WaterbalanceFD` in the `classic_waterbalance.py` file of PCSE, I found that in the case where `SS` is greater than 0.1, `AVAIL` is added twice with `RIRR` (i.e. Line 444). The infiltration rate has already been updated to the sum of potential infiltration rainfall, effective irrigation amount, and surface storage when `RINPRE = RINPRE + r.RIRR + s.SS` (i.e. Line 441). `RIRR` is added again when calculating `AVAIL`.
I would like to ask if my understanding is incorrect, or should the calculation of `AVAIL` (Line 444) be changed to `AVAIL = RINPRE - r.EVW`?
Looking forward to your reply, thank you!
Best regards,
Caroline
![Python](https://github.com/ajwdewit/pcse/assets/165553596/6846133a-9a8b-4499-b210-db76fea3a00d)

![Fortran](https://github.com/ajwdewit/pcse/assets/165553596/953f78ff-6ca0-4d61-b431-4728b896dbe4)

**Comment by ajwdewit** [comment]
Dear Caroline, 
Sorry for the slow response. I will have a look at it asap. 
Thanks,

Allard

**Comment by ajwdewit** [comment]
Dear Caroline,
I finally was able to look at it in more detail. I think you are correct, this was a case of double counting irrigation. I corrected in the code it will be available in next version of PCSE (currently 6.0.8).
Allard
