### ISSUE TITLE
Query regarding the version of pcse

### ISSUE THREAD

**Issue by Sharadyadav77** [ajwdewit/pcse#87]
Dear PCSE Development Team,

I hope this message finds you well.

I am currently working on implementing the WOFOST crop simulation model, which is built on the PCSE library. As per the documentation and resources I have referred to, the WOFOST model utilizes PCSE version 6.0.0. However, when attempting to install this specific version using pip, I encountered an issue indicating that  No matching distribution found for pcse==6.0.0

The exact command used was:

bash
Copy code
pip install pcse==6.0.0
And the resulting error message indicated that ERROR: Could not find a version that satisfies the requirement pcse==6.0.0 (from versions: 5.1.0, 5.1.1, 5.2.3, 5.2.4, 5.2.5, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.4.0, 5.4.1, 5.4.2, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 6.0.3, 6.0.6)
ERROR: No matching distribution found for pcse==6.0.0

Given this situation, I have a few questions and would appreciate your guidance:

Availability of PCSE Version 6.0.0:
Is there a way to access or obtain version 6.0.0 of the PCSE library? If this version is deprecated or removed, could you please provide the reasons for its unavailability?

Compatibility with WOFOST Model:
Could you confirm which versions of PCSE are fully compatible with the WOFOST model? If version 6.0.0 is not available, what would be the recommended version to use for optimal compatibility and functionality?

Upgrading Documentation:
If the documentation or resources are outdated and reference a non-existent version, is there an updated guide or best practices document that I could refer to for using the latest available version of PCSE (e.g., 6.0.6)?

Your assistance in resolving these questions would be immensely helpful, as it would enable me to proceed with the implementation without compatibility issues. If there are any specific steps or alternative solutions you recommend, please let me know.

Thank you for your time and support. I look forward to your response.

Best regards,

[Mr. Sharad Malhari Yadav]
[RS and GIS intern at Semantic Technologies private limited, Pune ,India]

**Comment by ajwdewit** [comment]
Dear Mr Sharad Malhari Yadav

Never write the dependency as pcse==6.0.0, just use pcse==6.0.  It will then automatically select the latest 6.0.x release, 6.0.6 in this case.

The last digit indicates bug fixes and we had some struggle pushing the 6.0 release. 

with best regards,

Allard
