### ISSUE TITLE
Value for parameter REALLOC_DVS missing

### ISSUE THREAD

**Issue by Acarlier-Osiris** [ajwdewit/pcse#88]
Dear ajwdewit,

I am encountering an issue with the Wofost81_WLP_CWB model when using the run_till() function. The specific error message I receive is:

Value for parameter REALLOC_DVS missing

This issue occurs on the first run. If I run the cell a second time, it executes without the initial error, but all the variables in the results are missing values except for SM and EVS.

![image](https://github.com/user-attachments/assets/20170f50-e587-4695-a800-a3ba27d453d8)

Hope you could fix it.

**Comment by ajwdewit** [comment]
Which crop are you running? It could be a problem with the new parameter files.

**Comment by Acarlier-Osiris** [comment]
On potato.

I think that was working with the beta version. not sure

**Comment by ajwdewit** [comment]
Is this already solved? Can you provide an example to reproduce the problem?

**Comment by Acarlier-Osiris** [comment]
I didn't see the README in WOFOST_crop_parameters. It now works using cropd = YAMLCropDataProvider(Wofost81_PP).

Thanks

**Comment by zhikaicheng** [comment]
Dear ajwdewit,

I also encountered this error with YAMLCropDataProvider.  This error was: "pcse.exceptions.ParameterError: Value for parameter REALLOC_DVS missing."

from pcse.input import YAMLCropDataProvider
data_dir = r'F:\WOFOST\WOFOST_crop_parameters-master\WOFOST_crop_parameters-master'
p = YAMLCropDataProvider(fpath=data_dir)
p.set_active_crop("wheat", "Winter_wheat_101")

wofost = Wofost81_NWLP_MLWB_SNOMIN(parameters, wdp, agro_dict)

Upon inspection I find that there is indeed no REALLOC_DVS parameter in the wheate.yaml file.
