### ISSUE TITLE
ExcelWeatherDataProvider: ValueError: need more than 5 values to unpack

### ISSUE THREAD

**Issue by fanquake** [ajwdewit/pcse#9]
Looking at the example for reading weather data on the develop branch, it keeps throwing this error. Everything else seems to be working fine.
```
from pcse.fileinput import ExcelWeatherDataProvider
weather = ExcelWeatherDataProvider("/Users/michael/Github/wheatsim/data/nl1.xlsx")
```

```
Warning: You are running a PCSE development version:  5.0.0
Traceback (most recent call last):
  File "wheat.py", line 12, in <module>
    weather = ExcelWeatherDataProvider("/Users/michael/Github/wheatsim/data/nl1.xlsx")
  File "/usr/local/lib/python2.7/site-packages/PCSE-5.0.0-py2.7.egg/pcse/fileinput/xlsweatherdataprovider.py", line 88, in __init__
    if not self._load_cache_file(self.fp_xls_fname):  # Cache file cannot be loaded
  File "/usr/local/lib/python2.7/site-packages/PCSE-5.0.0-py2.7.egg/pcse/fileinput/xlsweatherdataprovider.py", line 184, in _load_cache_file
    self._load(cache_filename)
  File "/usr/local/lib/python2.7/site-packages/PCSE-5.0.0-py2.7.egg/pcse/base_classes.py", line 1228, in _load
    (store, self.elevation, self.longitude, self.latitude, self.description, ETModel) = cPickle.load(fp)
ValueError: need more than 5 values to unpack
```

**Comment by ajwdewit** [comment]
Hi Michael,

Thanks for your mail. I will respond to your email on my WUR account 
later.

Regarding the error, are you loading an old cache file written by a 
previous version? I recently added the "ETmodel" to the tuple that is 
being written to the cache file, so it now expects a tuple of size 5 
when loading the cache file. See the _dump() and _load() functions here:
https://github.com/ajwdewit/pcse/blob/develop/pcse/base_classes.py#L1211

I thought that the error of loading an outdated cache file would be 
caught by each WeatherDataProvider, but this is not implemented for the 
ExcelWeatherDataProvider, I see here:
https://github.com/ajwdewit/pcse/blob/develop/pcse/fileinput/xlsweatherdataprovider.py#L178

So we probably need to change this code to:

     def _load_cache_file(self, xls_fname):

         cache_filename = self._find_cache_file(xls_fname)
         if cache_filename is None:
             return False
         else:
             try:
                 self._load(cache_filename)
                 return True
             except:
                 return False

regards,

Allard

**Comment by fanquake** [comment]
@ajwdewit Thanks for looking into it. 
I'm working with a brand new clone of the repo, so there are no old cache files.
That change seems to fix the issue, i'll test it further tonight.
