### ISSUE TITLE
If I know the flowering time of different wheat varieties, how can I assimilate it into WOFOST? Thank you.

### ISSUE THREAD

**Issue by tectal** [ajwdewit/pcse#91]
If I know the flowering time of different wheat varieties, how can I assimilate it into WOFOST? Thank you.

**Comment by ajwdewit** [comment]
Dear Tectal,

I don't think assimilation is the right strategy here: you have to define different varieties with adjusted values of the TSUM1 parameter.

Allard

**Comment by tectal** [comment]
Thank you for your answer.

I found that MIN=0.0003 and MAX=0.0003 of SSATB (Specific stem area as a function of development stage) in Gentle intro WOFOST-7_2_v20211123.pdf. Is there an error here? Why are the minimum and maximum values ​​the same?

![image](https://github.com/user-attachments/assets/be53423f-49ed-4fe1-ace0-ddd4b79d586f)

**Comment by ajwdewit** [comment]
That is mistake in the gentle intro. I think the value for SSATB should range between 0.0001 and 0.003

**Comment by tectal** [comment]
Thank you for your answer. I understand. I am a PhD student at Zhejiang University of China. I would like to ask if you and your team are recruiting postdoctoral fellows? I will graduate with a doctorate next year (2025) and now plan to apply for a postdoctoral fellow position. Thank you.

**Comment by ajwdewit** [comment]
WUR is recruiting post-docs regularly. Please have a look at: https://www.wur.nl/en/Jobs/Vacancies.htm

**Comment by tectal** [comment]
Thank you for your reply. : )
