### ISSUE TITLE
Minor mistake in wofost81.py

### ISSUE THREAD

**Issue by libaic7** [ajwdewit/pcse#94]
I have identified a potential minor issue within the wofost81.py module. The state variable named LEAF_REALLOCATED on line 271 appears to not defined. Upon reviewing its contextual usage, i question whether the correct variable name should actually be states.LV_REALLOCATED. Could you please verify this? Thank you.

# Reallocation rate in terms of loss of stem/leaf dry matter
if self.states.LV_REALLOCATED < self._WLV_REALLOC:
    r.REALLOC_LV = min(self._WLV_REALLOC * p.REALLOC_LEAF_RATE, self._WLV_REALLOC - self.states.LEAF_REALLOCATED)
else:
    r.REALLOC_LV = 0.

**Comment by ajwdewit** [comment]
Thanks for informing me. I will have a look at it.

**Comment by ajwdewit** [comment]
It is fixed in the version that is currently on the develop branch. I will move it to master soon and publish it as 6.0.9
